[customizations.installer.kickstart]
contents = """
# Prevents unecessary files getting created in /etc/firewalld/zones/.
firewall --use-system-defaults
"""

[customizations.installer.modules]
disable = [
    "org.fedoraproject.Anaconda.Modules.Security",
    "org.fedoraproject.Anaconda.Modules.Services",
    "org.fedoraproject.Anaconda.Modules.Subscription",
]
