name: ci
on:
  schedule:
    - cron: "44 8 * * 1,4"
  workflow_dispatch: null

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push image to GHCR
    runs-on: ubuntu-26.04

    permissions:
      contents: read
      packages: write  # to upload the image

    steps:
      - uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - run: podman info
        name: Print Podman version and other info

      - run: ./go.sh build
      - run: ./go.sh push-verms "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
