name: ci
on:
  schedule:
    - cron: "44 3 * * 1"
  workflow_dispatch: null

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push image to GHCR
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: ./go.sh build
      - run: ./go.sh push-verms ${{ github.token }}
